### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jeffdare** [tokoro10g/galileo-makefile#1]
Hi,

[root@bnegl123 comp]# make
/opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-g++ -O2 -pipe -g -feliminate-unused-debug-types -fpermissive -Wall -I /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/../include -I /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/../include/c++ -I /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/../lib/i586-poky-linux-uclibc/gcc/i586-poky-linux-uclibc/4.7.2/include    -m32 -march=i586 --sysroot=/opt/cross/i586-poky-linux-uclibc-x-tools -c -o helloworld.o helloworld.c
make: /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-g++: Command not found
make: **\* [helloworld.o] Error 127

[root@bnegl123 comp]# /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-g++
-bash: /opt/cross/i586-poky-linux-uclibc-x-tools/usr/bin/i586-poky-linux-uclibc/i586-poky-linux-uclibc-g++: /opt/clanton-tiny/1.4.2/sysroots/i586-pokysdk-linux/lib/ld-linux.so.2: bad ELF interpreter: No such file or directory

getting this error. Any help is appreciated. 

Thanks!!

**Comment by tokoro10g** [comment]
Thank you for opening the first issue!

It seems to be a problem with file permission, that is, i586-poky-linux-uclibc-g++ is not flagged as executable.
Please follow the procedure in the link below:
https://communities.intel.com/message/224087#224087

**Comment by jeffdare** [comment]
Thanks for the quick reply.. :)

But the file does have the permissions.

**Comment by jeffdare** [comment]
[root@bnegl123 i586-poky-linux-uclibc]# ls -l i586-poky-linux-uclibc-g++
-rwxr-xr-x 1 root root 570941 Aug 22 11:48 i586-poky-linux-uclibc-g++

But I think the issue is something else.. 

That is reason I copied the text in the second line. When I just ran i586-poky-linux-uclibc-g++, this is what I see.

[root@bnegl123 i586-poky-linux-uclibc]# ./i586-poky-linux-uclibc-g++
-bash: ./i586-poky-linux-uclibc-g++: /opt/clanton-tiny/1.4.2/sysroots/i586-pokysdk-linux/lib/ld-linux.so.2: bad ELF interpreter: No such file or directory

Why is it trying to find it in " /opt/clanton-tiny/1.4.2/sysroots/i586-pokysdk-linux/lib"..

**Comment by tokoro10g** [comment]
I found that the relocation of executable files is required to run the tools correctly.
The most simple and dirty workaround is to compile some blank sketch with Arduino IDE so that the interpreter of the compiler will relocated to the directory of Arduino IDE SDK path.
Referenced: https://wiki.archlinux.org/index.php/Step_By_Step_Debugging_Guide#Readelf

I'm going to write some document about this and, if possible, make shell script for easier installation.

**Comment by jeffdare** [comment]
Thanks for your comments. 

Yes... I tried to copy the devtools(i586-poky-linux-uclibc-x-tools) to /opt/clanton-tiny/1.4.2/sysroots/i586-pokysdk-linux and then tried to Make.. This worked.

**Comment by tokoro10g** [comment]
So, copying files to /opt/clanton-tiny/... and not to /opt/cross/... will work fine very easily, is it?

**Comment by jeffdare** [comment]
Yes... So I copied the entire toolchain to /opt/clanton-tiny/1.4.2/sysroots/i586-pokysdk-linux and it worked.

**Comment by tokoro10g** [comment]
Thanks for reporting!
This should be done with small fixes so I will make it quickly!
